update

diff --git a/scripts/update b/scripts/update
--- a/scripts/update
+++ b/scripts/update
@@ -19,10 +19,15 @@ if [ ! -e /etc/rc2.d/S50oyapi ]; then
 fi
 
 echo -e "UPDATE\t: Retrieving latest github content..."
-git pull
+git pull | tee /tmp/git.log
 RC=$?; if [ "$RC" != "0" ]; then 
     echo -e "ERROR\t: Could not update"
     exit $RC
+fi
+grep Already /tmp/git.log
+RC=$?; if [ "$RC" == "0" ]; then
+    echo -e "UPDATE\t: Your system is up-to-date. No further action required"
+    exit 0
 fi
 sync
 
